//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Model.Models.SJM;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armazem
    {

        [Key]
        public string armazemStamp { get; set; }
        public string descricao { get; set; }
        public string numeroArmazem { get; set; }
        public string localizacao { get; set; }
        public string contacto { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

    }
}
