//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtigoContrato
    {
        [Key]
        public string artigoContratoStamp { get; set; }
        [ForeignKey("Contrato")]
        public string contratoStamp { get; set; }
        public string descricao { get; set; }
        public int quantidade { get; set; }
        public Nullable<int> tamanho { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        [ForeignKey("Artigo")]
        public string artigoStamp { get; set; }
    
        public virtual Artigo Artigo { get; set; }
        public virtual Contrato Contrato { get; set; }
    }
}
