//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artigo
    {
      
        [Key]
        public string artigoStamp { get; set; }
        [ForeignKey("ArtigoGeral1")]
        public string artigoGeralStamp { get; set; }
        public string codArtigo { get; set; }
        public string descricaoartigo { get; set; }
        public string artigogeral { get; set; }
        public string orgao { get; set; }
        public string grupo { get; set; }
        public string sexo { get; set; }
        public Nullable<bool> policiaMilitar { get; set; }
        public Nullable<bool> unidCerimonial { get; set; }
        public Nullable<bool> unifTrabalho { get; set; }
        public Nullable<bool> desportivo { get; set; }
        public Nullable<bool> domando { get; set; }
        public Nullable<bool> daraquedista { get; set; }
        public Nullable<bool> fuzileiro { get; set; }
        public Nullable<bool> piloto { get; set; }
        public Nullable<bool> complementar { get; set; }
        public Nullable<bool> ofGen { get; set; }
        public Nullable<bool> ofSup { get; set; }
        public Nullable<bool> ofSub { get; set; }
        public Nullable<bool> sargento { get; set; }
        public Nullable<bool> praca { get; set; }
        public int norma { get; set; }
        public string tempoUtil { get; set; }
        public string tempoutilMesesAnos { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }


        public virtual ArtigoGeral ArtigoGeral1 { get; set; }
        public virtual ICollection<ArtigoContrato> ArtigoContrato { get; set; }
        public virtual ICollection<Existencia> Existencia { get; set; }
    }
}
