//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
      

        [Key]
        public string contratoStamp { get; set; }
        public string nrContrato { get; set; }
        public string fornecedor { get; set; }
        public string contacto { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        public string descricaocontrato { get; set; }
        public string abreviaturaFornecedor { get; set; }
    
        public virtual ICollection<ArtigoContrato> ArtigoContrato { get; set; }
    }
}
