//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [Key]
        public string cursoStamp { get; set; }
        public int codCurso { get; set; }
        public string descricao { get; set; }
        public Nullable<bool> tipo { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        public string abreviatura { get; set; }
    }
}
