//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desconto
    {
        [Key]
        public string descontoStamp { get; set; }
        public int codDesconto { get; set; }
        public string descricao { get; set; }
        public int percentgDesconto { get; set; }
        public string obsDesconto { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        [ForeignKey("MilSalario")]
        public string milStamp { get; set; }
    
        public virtual MilSalario MilSalario { get; set; }
    }
}
