//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Model.Models.SJM;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrada
    {
        [Key]
        public string entradaStamp { get; set; }
        [ForeignKey("Existencia")]
        public string existenciaStamp { get; set; }
        public int quantidade { get; set; }
        public string dataEntrada { get; set; }

        [ForeignKey("Unidade")]
        public string unidadeStamp { get; set; }
        public string orgao { get; set; }
        public int numeroGR { get; set; }
        public Nullable<decimal> pUnit { get; set; }
        public Nullable<decimal> pTotal { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        public string numeroContrato { get; set; }
        public string NumeroParaImpressao { get; set; }
    
        public virtual Existencia Existencia { get; set; }
        public virtual Unidade Unidade { get; set; }
    }
}
