//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Model.Models.SJM;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escalao
    {
        [Key]
        public string escalaoStamp { get; set; }
        public int codEscalao { get; set; }
        public string patente { get; set; }
        public string escalaoUcerm1 { get; set; }
        public string ESCALÃO_I { get; set; }
        public string ESCALÃO_II { get; set; }
        public string ESCALÃO_III { get; set; }
        public string ESCALÃO_IV { get; set; }
        public string ESCALÃO_V { get; set; }
        public string obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        [ForeignKey("Pat")]
        public string patStamp { get; set; }
    
        public virtual Pat Pat { get; set; }
    }
}
