//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Existencia
    {
        [Key]
        public string existenciaStamp { get; set; }
        [ForeignKey("Artigo")]
        public string artigoStamp { get; set; }
        public string tamanho { get; set; }
        public int quantidadeActual { get; set; }
        public string armazemStamp { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }


        public virtual Artigo Artigo { get; set; }
        public virtual ICollection<Entrada> Entrada { get; set; }
        public virtual ICollection<Fornecimento> Fornecimento { get; set; }
    }
}
