//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedor
    {
       
        // [ForeignKey("Artigo")]
        [Key]
        public string fornecedorStamp { get; set; }
        public string fornecedorNome { get; set; }
        public string fornecedorAbreviatura { get; set; }
        public string fornecedorContacto { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        public string codigo { get; set; }
    }
}
