//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Model.Models.SJM;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecimento
    {


        // [ForeignKey("Artigo")]
        [Key]
        public string fornecimentoStamp { get; set; }
         [ForeignKey("Unidade")]
        public string? unidadeStamp { get; set; }
        [ForeignKey("Mil")]
        public string? milStamp { get; set; }
        [ForeignKey("Existencia")]
        public string? existenciaStamp { get; set; }
        [ForeignKey("Subunidade")]
        public string? subunidadeStamp { get; set; }
        public int quantidade { get; set; }
        public string dataFornecimento { get; set; }
        public int numeroGR { get; set; }
        public bool jarecebeu { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        public string NomeOrgaoUnidade { get; set; }
        public virtual Existencia Existencia { get; set; }
        public virtual ICollection<Entrega> Entrega { get; set; }
        public virtual Mil Mil { get; set; }
        public virtual Subunidade Subunidade { get; set; }
        public virtual Unidade Unidade { get; set; }
    }
}
