//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilEmFor
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string milEmForStamp { get; set; }
        public int codMilEmFor { get; set; }
        public bool tipo { get; set; }
        public string curso { get; set; }
        public string adquirEspecial { get; set; }
        public string custos { get; set; }
        public string anoFrequentar { get; set; }
        public string dataInicio { get; set; }
        public string dataTermino { get; set; }
        public string duracao { get; set; }
        public string duracaoNormal { get; set; }
        public string nivel { get; set; }
        public string nivelAtingir { get; set; }
        public bool tipoInstituicao { get; set; }
        public string instituicao { get; set; }
        public string obs { get; set; }
        public int codPpais { get; set; }
        public string pais { get; set; }
        public int codProvincia { get; set; }
        public string provincia { get; set; }
        public int codDistrito { get; set; }
        public string distrito { get; set; }
        public int codPostoAdm { get; set; }
        public string postoAdm { get; set; }
        public int codLocalidade { get; set; }
        public string localidade { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        [ForeignKey("Mil")]
        public string milStamp { get; set; }
    
        public virtual Mil Mil { get; set; }
    }
}
