//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilEspecial
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string milEspecialStamp { get; set; }
        public int codMilEspecial { get; set; }
        public int codRamo { get; set; }
        public string ramo { get; set; }
        public int codEspecial { get; set; }
        public string especial { get; set; }
        public Nullable<int> codSubEspecial { get; set; }
        public string subEspecial { get; set; }
        public string dataEspecial { get; set; }
        public string numOS { get; set; }
        public string obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        public string especialStamp { get; set; }
        [ForeignKey("Mil")]
        public string milStamp { get; set; }
        public virtual Mil Mil { get; set; }
        public virtual ICollection<MilSubEspecial> MilSubEspecial { get; set; }
    }
}
