//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilFa
    {
        // [ForeignKey("Artigo")]
        [Key, ForeignKey("Mil")]
        public string milStamp { get; set; }
        public int codMilFa { get; set; }
        public string falecData { get; set; }
        public string falecLocal { get; set; }
        public string circunstancias { get; set; }
        public string enterroData { get; set; }
        public string enterroLocal { get; set; }
        public string numCampa { get; set; }
        public string numCertObito { get; set; }
        public string obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }


        public virtual Mil Mil { get; set; }
    }
}
