//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilFuncao
    {// [ForeignKey("Artigo")]
        [Key]
        public string milFuncaoStamp { get; set; }
        [ForeignKey("Mil")]  
        public string milStamp { get; set; }
        public int codMilFuncao { get; set; }
        public string funcao { get; set; }
        public string numOS { get; set; }
        public string dataOS { get; set; }
        public string dataInicio { get; set; }
        public string dataTermino { get; set; }
        public string obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        public string orgao { get; set; }
        public string unidade { get; set; }
        public string subunidade { get; set; }
        public string subunidade1 { get; set; }
        public string subunidade2 { get; set; }
        public string orgaoStamp { get; set; }
        public string unidadeStamp { get; set; }
        public string subunidadeStamp { get; set; }
        public string subunidade1Stamp { get; set; }
        public string subunidade2Stamp { get; set; }
    
        public virtual Mil Mil { get; set; }
    }
}
