//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilIDigital
    {
        [ForeignKey("Mil")]
        // [ForeignKey("Artigo")]
        [Key]
        public string milStamp { get; set; }
        public string caminhoPolegarE { get; set; }
        public byte[] polegarE { get; set; }
        public string caminhoIndicadorE { get; set; }
        public byte[] indicadorE { get; set; }
        public string caminhoPolegarD { get; set; }
        public byte[] polegarD { get; set; }
        public string caminhoIndicadorD { get; set; }
        public byte[] indicadorD { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }


        public virtual Mil Mil { get; set; }
    }
}
