//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilLice
    {

        // [ForeignKey("Artigo")]
        [Key]
        public string milLiceStamp { get; set; }
        public int codMilLice { get; set; }
        public string licenca { get; set; }
        public string licencaData { get; set; }
        public string dataTermino { get; set; }
        public string duracao { get; set; }
        public string obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        public string licencaStamp { get; set; }
        [ForeignKey("Mil")]
        public string milStamp { get; set; }
        public virtual Mil Mil { get; set; }
    }
}
