//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilMed
    {
        [Key, ForeignKey("Mil")]
        public string milStamp { get; set; }
        public int codMil { get; set; }
        public Nullable<decimal> altura { get; set; }
        public Nullable<decimal> braco { get; set; }
        public Nullable<decimal> cabeca { get; set; }
        public Nullable<decimal> pescoco { get; set; }
        public Nullable<decimal> peito { get; set; }
        public Nullable<decimal> cintura { get; set; }
        public Nullable<decimal> ancas { get; set; }
        public Nullable<decimal> entrepernas { get; set; }
        public Nullable<decimal> calcado { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<decimal> ombros { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }


        public virtual Mil Mil { get; set; }
    }
}
