//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilPeEmerg
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string milPeEmergStamp { get; set; }
        public int codMilPeEmerg { get; set; }
        public string nome { get; set; }
        public string grau { get; set; }
        public string nascProv { get; set; }
        public int codNascProv { get; set; }
        public string resProv { get; set; }
        public int codResProv { get; set; }
        public string resDist { get; set; }
        public int codResDist { get; set; }
        public string resPosto { get; set; }
        public Nullable<int> codResPostAdm { get; set; }
        public string resLocal { get; set; }
        public Nullable<int> codResLocal { get; set; }
        public string resBairro { get; set; }
        public string resAvenida { get; set; }
        public string resQuarteirao { get; set; }
        public string numCasa { get; set; }
        public string obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        [ForeignKey("Mil")]
        public string milStamp { get; set; }
    
        public virtual Mil Mil { get; set; }
    }
}
