//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilProm
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string milPromStamp { get; set; }
        public int codMilProm { get; set; }
        public string categoria { get; set; }
        public string patente { get; set; }
        public string tipoPromocao { get; set; }
        public string dataOS { get; set; }
        public string numOS { get; set; }
        public string obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        public string patStamp { get; set; }
        [ForeignKey("Mil")]
        public string milStamp { get; set; }

        public virtual Mil Mil { get; set; }
    }
}
