//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilReg
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string milRegStamp { get; set; }
        public Nullable<int> codReg { get; set; }
        public string dataReg { get; set; }
        public string numOS { get; set; }
        public string regime { get; set; }
        public string obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        [ForeignKey("Reg")]
        public string regStamp { get; set; }
        [ForeignKey("Mil")]
        public string milStamp { get; set; }
        public virtual Mil Mil { get; set; }
    }
}
