//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilReco
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string milRecoStamp { get; set; }
        public int codMilReco { get; set; }
        public string tipoDistincao { get; set; }
        public string concessaoDoc { get; set; }
        public string orgao { get; set; }
        public string data { get; set; }
        public string motivo { get; set; }
        public string obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        [ForeignKey("Mil")]
        public string milStamp { get; set; }

        public virtual Mil Mil { get; set; }
    }
}
