//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilSalMensal
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string milSalMensalStamp { get; set; }
        public long nim { get; set; }
        public string nome { get; set; }
        public string regime { get; set; }
        public string patente { get; set; }
        public string especialidade { get; set; }
        public string mes { get; set; }
        public int ano { get; set; }
        public decimal bonusEspecial { get; set; }
        public decimal sQTC { get; set; }
        public decimal subsPosto { get; set; }
        public decimal subSaudeMG95 { get; set; }
        public decimal subSaudeTSS75 { get; set; }
        public decimal subSaudeRisco15 { get; set; }
        public decimal subSaudeSCET25 { get; set; }
        public decimal subSaudeSEXC40 { get; set; }
        public decimal suplementoChefia25 { get; set; }
        public decimal suplementoSCET10 { get; set; }
        public decimal suplementoRisco15 { get; set; }
        public decimal forcaEspecial40 { get; set; }
        public decimal forcaEspecial50 { get; set; }
        public decimal forcaEspecial60 { get; set; }
        public decimal desconto2 { get; set; }
        public decimal desconto7 { get; set; }
        public decimal liquidoActual { get; set; }
        public decimal escalao1 { get; set; }
        public decimal escalao2 { get; set; }
        public decimal escalao3 { get; set; }
        public decimal escalao4 { get; set; }
        public decimal escalao5 { get; set; }
        public decimal subAlimentacao { get; set; }
        public decimal subTrinta30 { get; set; }
        public decimal totalDesconto { get; set; }
        public decimal outroSubsidio { get; set; }
        public decimal totalBonus { get; set; }
        public decimal liquidoRecebe { get; set; }
        public long contaBanco { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        [ForeignKey("MilSalario")]
        public string milStamp { get; set; }
    
        public virtual MilSalario MilSalario { get; set; }
    }
}
