//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilSalario
    {

        [Key, ForeignKey("Mil")]
        public string milStamp { get; set; }
        public Nullable<bool> uCerimonial { get; set; }
        public Nullable<bool> saudeMilitar { get; set; }
        public Nullable<bool> recebePatente { get; set; }
        public Nullable<bool> recebeSqtc { get; set; }
        public string escalao { get; set; }
        public string sQTC { get; set; }
        public string nivelSalarial { get; set; }
        public string nomeBanco { get; set; }
        public string nrConta { get; set; }
        public string nib { get; set; }
        public string obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        public virtual ICollection<Desconto> Desconto { get; set; }
        public virtual Mil Mil { get; set; }
        public virtual ICollection<MilSalMensal> MilSalMensal { get; set; }
        public virtual ICollection<Subsidio> Subsidio { get; set; }
        public virtual ICollection<Suplemento> Suplemento { get; set; }
    }
}
