//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilSitCrim
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string milSitCrimStamp { get; set; }
        public int codMilSitCrim { get; set; }
        public string orgao { get; set; }
        public string infraccao { get; set; }
        public string numProcesso { get; set; }
        public string processodata { get; set; }
        public string pena { get; set; }
        public string detencaoData { get; set; }
        public string condenacaoData { get; set; }
        public string localPrisao { get; set; }
        public string solturaData { get; set; }
        public string numDocSoltura { get; set; }
        public string obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        [ForeignKey("Mil")]
        public string milStamp { get; set; }
    
        public virtual Mil Mil { get; set; }
    }
}
