//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilSitDisc
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string milSitDiscStamp { get; set; }
        public int codMilSitDisc { get; set; }
        public string orgao { get; set; }
        public string numOS { get; set; }
        public string infracao { get; set; }
        public string numProcesso { get; set; }
        public string dataProcesso { get; set; }
        public string medTomadas { get; set; }
        public string dataInicioMedida { get; set; }
        public string dataTerminoMedida { get; set; }
        public string obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        [ForeignKey("Mil")]
        public string milStamp { get; set; }
    
        public virtual Mil Mil { get; set; }
    }
}
