//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilSubEspecial
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string milSubEspecialStamp { get; set; }
        [ForeignKey("MilEspecial")]
        public string milEspecialStamp { get; set; }
        public string SubespecialStamp { get; set; }
        public Nullable<System.DateTime> dataSubEspecial { get; set; }
        public string numOS { get; set; }
        public string Obs { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }


        public virtual MilEspecial MilEspecial { get; set; }
    }
}
