//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualifcTecnica
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string qualifcTecnicaStamp { get; set; }
        public int codQualifTecnica { get; set; }
        public string descricao { get; set; }
        public string grupoSalarial { get; set; }
        public decimal nível_IV { get; set; }
        public decimal nível_III { get; set; }
        public decimal nível_II { get; set; }
        public decimal nível_I { get; set; }
        public decimal Com_Mais_de_10_anos { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

    }
}
