//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubEspecial
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string subEspecialStamp { get; set; }
        public int codSubespecial { get; set; }
        public string descricao { get; set; }
        public int codEspecial { get; set; }
        public string especialidade { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        [ForeignKey("Especial")]
        public string especialStamp { get; set; }
    
        public virtual Especial Especial { get; set; }
    }
}
