//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using Model.Models.SJM;
    using System;
    using System.Collections.Generic;
    
    public partial class Subunidade1
    {

        // [ForeignKey("Artigo")]
        [Key]

        public string subunidade1Stamp { get; set; }
        public int codSubunidade1 { get; set; }
        public string descricao { get; set; }
        public string subunidade { get; set; }
        public string codOrgao { get; set; }
        public string orgao { get; set; }
        public string unidade { get; set; }
        public int organica { get; set; }
        public int totalOfSup { get; set; }
        public int totalCor { get; set; }
        public int totalTteCor { get; set; }
        public int totalMaj { get; set; }
        public int totalOfSub { get; set; }
        public int totalCap { get; set; }
        public int totalTte { get; set; }
        public int totalTteMil { get; set; }
        public int totalAlf { get; set; }
        public int totalAlfMil { get; set; }
        public int totalSarg { get; set; }
        public int totalInt { get; set; }
        public int totalSub { get; set; }
        public int totalPriSar { get; set; }
        public int totalSegSar { get; set; }
        public int totalTerSar { get; set; }
        public int totalFur { get; set; }
        public int totalPra { get; set; }
        public int totalPriCab { get; set; }
        public int totalSegCab { get; set; }
        public int totalSold { get; set; }
        public string provincia { get; set; }
        public int codProvincia { get; set; }
        public string distrito { get; set; }
        public int codDistrito { get; set; }
        public string postoAdm { get; set; }
        public int codPostoAdm { get; set; }
        public string localidade { get; set; }
        public int codLocalidade { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }

        [ForeignKey("Subunidade")]
        public string subunidadeStamp { get; set; }
        public Nullable<int> totalOf { get; set; }
        public virtual Subunidade Subunidade { get; set; }
        public virtual ICollection<Subunidade2> Subunidade2 { get; set; }
    }
}
