//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Model.Models.SGPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suplemento
    {
        // [ForeignKey("Artigo")]
        [Key]
        public string suplementoStamp { get; set; }
        public int codSuplemento { get; set; }
        public string descricao { get; set; }
        public int percentgSuplemento { get; set; }
        public string obsSuplemento { get; set; }
        public string inseriu { get; set; }
        public DateTime? inseriuDataHora { get; set; }
        public string alterou { get; set; }
        public DateTime? alterouDataHora { get; set; }


        [ForeignKey("MilSalario")]
        public string milStamp { get; set; }
    
        public virtual MilSalario MilSalario { get; set; }
    }
}
