using System.ComponentModel.DataAnnotations;

namespace Model.Models.Facturacao
{
public  class A_param
    {
        [Key]
        public string a_paramstamp { get; set; }
        public string qmc { get; set; }
        public DateTime qmcdathora { get; set; }
        public string qma { get; set; }
        public DateTime qmadathora { get; set; }
        public decimal ftmax { get; set; }
        public decimal rfmax { get; set; }
        public decimal despmax { get; set; }
        public decimal dumax { get; set; }
        public decimal rdcodtesoura { get; set; }
        public string rdcontatesoura { get; set; }
        public bool rdalttesoura { get; set; }
        public decimal rccodtesoura { get; set; }
        public string rccontatesoura { get; set; }
        public bool rcalttesoura { get; set; }
        public decimal rpcodtesoura { get; set; }
        public string rpcontatesoura { get; set; }
        public bool rpalttesoura { get; set; }
        public decimal pgcodtesoura { get; set; }
        public string pgcontatesoura { get; set; }
        public bool pgalttesoura { get; set; }
        public bool ftaberto { get; set; }
        public string separador { get; set; }
        public string ponto { get; set; }
        public decimal AVMAX { get; set; }
        public decimal ivcodentr { get; set; }
        public string ivdescentr { get; set; }
        public decimal ivcodsai { get; set; }
        public string ivdescsai { get; set; }
        public string dseparador { get; set; }
        public bool UsaPosRest { get; set; }
        public bool UsaPosQtt { get; set; }
        public string MaskPosQtt { get; set; }
        public string MaskPosValor { get; set; }
        public string motivoiva { get; set; }
        public string cpextcccl { get; set; }
        public string cpextccfn { get; set; }
        public string cprd { get; set; }
        public string cprdf { get; set; }
        public string cplitsdocs { get; set; }
        public string cpmvtcc { get; set; }
        public string motivoivaeng { get; set; }
        public bool usadi { get; set; }
        public bool usafact { get; set; }
        public bool usafacc { get; set; }
        public string smtpserver { get; set; }
        public decimal smtpport { get; set; }
        public string outgoingemail { get; set; }
        public string outgoingpassword { get; set; }
        public string destinationemail { get; set; }
        public string subj { get; set; }
        public string emailtext { get; set; }
        public decimal tipobase { get; set; }
        public string formapag { get; set; }
        public decimal codtiposgs { get; set; }
        public string desctiposgs { get; set; }
        public decimal codsgs { get; set; }
        public string descsgs { get; set; }
        public string SMTPServerp { get; set; }
        public decimal SMTPPortp { get; set; }
        public string outGoingEmailp { get; set; }
        public string outGoingPasswordp { get; set; }
        public string destinationEmailp { get; set; }
        public string subjp { get; set; }
        public string emailTextp { get; set; }
        public string pathponto { get; set; }
        public bool usaanexo { get; set; }
        public decimal temailgest { get; set; }
        public decimal temailpess { get; set; }
        public decimal contacc { get; set; }
        public decimal fncpgc { get; set; }
        public decimal clpgc { get; set; }
        public string grupo { get; set; }
        public string marca { get; set; }
        public string submarca { get; set; }
        public bool nopend { get; set; }
        public decimal codtzpos { get; set; }
        public string contastesourapos { get; set; }
        public decimal comissao { get; set; }
        public bool qttsoma { get; set; }
        public bool gointro { get; set; }
        public bool noaltpreco { get; set; }
        public bool askremline { get; set; }
        public bool refauto { get; set; }
        public string exprefauto { get; set; }
        public string extuser { get; set; }
        public string extpassw { get; set; }
        public string extdatabase { get; set; }
        public string extinstance { get; set; }
        public bool ShowCapBarras { get; set; }
        public string bdimagens { get; set; }
        public decimal percSeguro { get; set; }
        public decimal percFrete { get; set; }
        public decimal valormin { get; set; }
        public decimal valormin2 { get; set; }
        public bool tabhonor { get; set; }
        public bool naoresumo { get; set; }
        public bool ivaagencia { get; set; }
        public string PastaScan { get; set; }
        public string tipoimg { get; set; }
        public bool usaexternalbd { get; set; }
        public bool usaestab { get; set; }
        public bool usacomerc { get; set; }
        public decimal ano { get; set; }
        public bool autointcl { get; set; }
        public string diarioTrf { get; set; }
        public decimal noDiTrf { get; set; }
        public decimal nDocContTrf { get; set; }
        public string descDocTrf { get; set; }
        public string diarioDp { get; set; }
        public decimal noDiDp { get; set; }
        public decimal nDocContDp { get; set; }
        public string descDocDp { get; set; }
        public string diarioMvt { get; set; }
        public decimal noDiMvt { get; set; }
        public decimal nDocContMvt { get; set; }
        public string descDocMvt { get; set; }
        public bool autointfnc { get; set; }
        public bool usames { get; set; }
        public string contmascara { get; set; }
        public bool autointeg { get; set; }
    }
}
